### ISSUE TITLE
fofa识别是指只通过fofa获取url地址，识别还是本地识别吗？fofa直接识别组件信息好像只对企业会员开放

### ISSUE THREAD

**Issue by hyccgit** [s7ckTeam/Glass#10]
12345

**Comment by nosafer** [comment]
fofa采集url 识别还是本地识别

**Comment by sinlee1** [comment]
4个API都进行了添加，但如果只用**-i**参数的话，默认只进行fofa的搜索。能添加一个对所有API进行一起检测的参数码？而不需要单独通过**-s**的方式进行一个一个测试。且文档中并没有说明**360**和**shodan**的单独测试参数，可能我看漏了。@nosafer

**Comment by s7ckTeam** [comment]
> 4个API都进行了添加，但如果只用-i参数的话，变成只进行fofa的搜索。能添加一个对所有API进行一起检测的参数吗？而不需要单独通过-s的方式进行一个一个测试。且文档中并没有说明360和shodan的单独测试参数，可能我看漏了。@nosafer

目前项目整体已经进行了修改
1.原版本默认-i，考虑到大部分人没有fofa高级版api,故改称让用户自主选填参数
2.后续版本会放出一起检测和结果对比输出
3.4个参数目前只放出fofa和zoomeye
4.-s参数目前是为了大家对搜索结果进行对比

**Comment by sinlee1** [comment]
期待新版本更新，同时感谢提供此工具。

**Comment by s7ckTeam** [comment]
感谢支持，请持续关注更新
