### ISSUE TITLE
异常报错及数据准确性反馈

### ISSUE THREAD

**Issue by sinlee1** [s7ckTeam/Glass#11]
- 开启代理的情况下导致报错 
```
python3 Glass.py -i 161.64.198.3/16 -s eye --proxy-list cn
```
![image](https://user-images.githubusercontent.com/29684167/105170050-5cac2500-5b57-11eb-9c10-439f39c643a4.png)

- 不开启代理的情况下没有报错，但结果不准确。

- Glass结果
![image](https://user-images.githubusercontent.com/29684167/105170289-adbc1900-5b57-11eb-94f4-67f3019acb14.png)
-页面查询结果
![image](https://user-images.githubusercontent.com/29684167/105170309-ba407180-5b57-11eb-825e-2cedd49220e4.png)
Glass是去重后的结果？
@nosafer

**Comment by nosafer** [comment]
python3 Glass.py -i 161.64.198.3/16 -s eye --proxy cn  这个是使用代理  --proxy-list cn 是获取，不带入使用

**Comment by sinlee1** [comment]
直接`--proxy`有效，但结果很少，C段结果比B段多不确定是什么原因。@nosafer

**Comment by nosafer** [comment]
我刚用API用web获取，一样很少，所有不是该工具原因

**Comment by nosafer** [comment]
一切以api数据为准，不参照直接搜索的数据。

**Comment by sinlee1** [comment]
Thx,可能是fofa的限制。
