### ISSUE TITLE
批量扫描IP报错

### ISSUE THREAD

**Issue by TerickJojo** [s7ckTeam/Glass#12]
如图
![image](https://user-images.githubusercontent.com/24235319/105189651-27600100-5b70-11eb-80af-24c7fcf01cfb.png)

批量URL正常

**Comment by nosafer** [comment]
确保api地址正确，这个提示是没获取到信息

**Comment by TerickJojo** [comment]
> 确保api地址正确，这个提示是没获取到信息

已解决，api过期了，谢谢了
