### ISSUE TITLE
对于本地和fofa识别指纹的疑问

### ISSUE THREAD

**Issue by Ksharp12138** [s7ckTeam/Glass#2]
想请教一下为什么url是本地识别，ip是fofa api识别，想问一下这两者有什么区别么，两者为啥不能公用，真心问

**Comment by nosafer** [comment]
IP的话如果是url（http://127.0.0.1:8080/），也算是本地识别，纯IP的话就是利用fofa对IP进行搜索，做URL采集，然后再比对

说白了就是一个是用API对IP进行搜索，采集URL进行识别，一个就是不需要采集，直接识别。
