### ISSUE TITLE
标题乱码问题，目标站编码格式为utf-8

### ISSUE THREAD

**Issue by sv3nbeast** [s7ckTeam/Glass#3]
![image](https://user-images.githubusercontent.com/55974091/103846400-f5af5a80-50d8-11eb-9313-ead250a26651.png)

检测了一些url站，网站编码格式都是utf-8,有的标题正常，有的乱码
其他类似工具Ehole不会乱码，请检查

同时感谢开源此工具

**Comment by nosafer** [comment]
已经再修复，谢谢反馈。

**Comment by sinlee1** [comment]
![image](https://user-images.githubusercontent.com/29684167/103986464-bd397a80-51c5-11eb-9bfe-8ffabeadfce1.png)
GBK编码异常 @nosafer

**Comment by nosafer** [comment]
发下网址吧

**Comment by sinlee1** [comment]
地址：202.86.180.130/24  @nosafer

**Comment by nosafer** [comment]
你先下载新版吧，刚刚简单的解决了下
