### ISSUE TITLE
目标URL数量较多时的结果准确问题

### ISSUE THREAD

**Issue by sv3nbeast** [s7ckTeam/Glass#9]
![image](https://user-images.githubusercontent.com/55974091/104798731-0a3fd100-5804-11eb-94b7-e5c1b1936470.png)

图片展示的是开启代理和不开启代理后的结果准确率问题

其实还有另外一种可能存在的问题:
当目标URL较大的，只使用-w sub.txt  每次获取的结果url数量也是不同的，有些url确实无法访问，有些url是响应较慢，导致每次的结果是不同的，如何增加结果准确率也是一个可优化的地方

当然这是大部分工具有批量功能时的通病，结果或多或少会存在部分的误差

同时感谢提供此工具

**Comment by nosafer** [comment]
这个和设置的超时有关的，可以提高准确率，设置重连，但是会大幅度降低速度，建议分批扫，而且代理之后是因为代理之后的响应速度会变慢，而且有些网站开代理，会访问不了，正常现象。

**Comment by nosafer** [comment]
还有就是代理的时候，建议使用cn 不要all
